### ISSUE TITLE
Automatically add "scan approved" label if the pull request author has write access to the repository

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/crda#29]
In this case, we can bypass the PR security process since the committer already has write access/

**Comment by divyansh42** [comment]
Just the `CRDA scan approved` and `CRDA scan pending ` label or other labels too?

**Comment by tetchel** [comment]
the passed/failed labels still make sense to add

**Comment by divyansh42** [comment]
Yeah, that makes sense.
